inputs_def:
  - handle: base
    json_schema:
      type: string
    value: http://192.168.8.100:8000/v1
  - handle: key
    description: Input
    json_schema:
      type: string
    value: "123456"
  - handle: model
    json_schema:
      type: string
    value: gemma-2-27b-it
  - handle: messages
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          role:
            type: string
            pattern: \b(system|assistant|user)\b
          content:
            type: string
    value:
      - role: user
        content: 你好
outputs_def:
  - handle: output
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
icon: ":skill-icons:typescript:"
description: 调用openai聊天
